name: CI Client

on:
  push:
    branches: [main]
    paths:
      - "client/**"
      - ".github/workflows/ci-client.yml"
  pull_request:
    paths:
      - "client/**"
      - ".github/workflows/ci-client.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Lint
        run: bun run lint
